# Generated by Django 3.2.5 on 2021-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cellno',
            field=models.CharField(default='00000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='xxx@xxx.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
