# Generated by Django 3.2.5 on 2021-07-28 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0003_food_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webkiosk.customer'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webkiosk.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webkiosk.orders')),
            ],
        ),
    ]
