# Generated by Django 3.2.5 on 2021-08-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0004_auto_20210728_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='food',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webkiosk.food'),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cellno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
