# Generated by Django 3.2.5 on 2021-08-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webkiosk', '0007_auto_20210802_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webkiosk.food'),
        ),
    ]
